Refactored smtp mail driver
feather-framework/feather-mail-driver-smtp pull request #2
Opened 2023-12-01 13:32 UTC by mzpx

- fixed for service builder protocol

2023-12-01 16:16 UTC, tib requested changes

2023-12-01 16:16 UTC, tib commented on Tests/FeatherMailDriverSMTPTests/FeatherMailDriverSMTPTests.swift
> +                id: MailServiceID.custom("smtp")
We should use the `addMail` function with the default id, instead of explicitly providing the id & using the service `add` method.

2023-12-01 16:16 UTC, tib commented on Tests/FeatherMailDriverSMTPTests/FeatherMailDriverSMTPTests.swift
> +            let mail = try await registry.mail(MailServiceID.custom("smtp"))
This could be reverted if you use addMail with the default id.

2024-01-02 08:11 UTC, tib approved these changes

2024-01-04 13:36 UTC, tib commented
@mzpx visionOS support is missing from the `Package.swift` file.
Could you add that please? Thanks.

2024-01-05 07:43 UTC, mzpx commented
I've fixed the visionOS support.

2024-01-05 08:41 UTC, tib approved these changes

2024-01-05 08:41 UTC, merged